Repository DataDog/mkdocs-click, pull requests merged in 2021-02, with the labels that each got.

#29 Keep --help as part of options raw output
  mkdocs_click/_docs.py
  tests/app/expected.md
  tests/unit/test_docs.py
Labels: changelog/Changed, rendering

#30 Clean up table formatting
  README.md
  mkdocs_click/_docs.py
  mkdocs_click/_extension.py
  tests/unit/test_docs.py
Labels: rendering

#24 Use prog_name for usage
  mkdocs_click/_docs.py
  mkdocs_click/_extension.py
  tests/app/cli.py
  tests/test_extension.py
  tests/unit/test_docs.py
Labels: changelog/Added

#31 Make usage and options headings bold
  mkdocs_click/_docs.py
  tests/app/expected.md
  tests/unit/test_docs.py
Labels: changelog/Fixed, rendering

#32 Tweak tests
  tests/test_docs.py
  tests/test_loader.py
  tests/test_processing.py
  tests/unit/__init__.py
Labels: tooling

#33 Rename level=... to depth=... for consistency
  mkdocs_click/_docs.py
  mkdocs_click/_extension.py
  tests/test_docs.py
Labels: refactor

#36 Allow using full command paths in headers
  README.md
  mkdocs.yml
  mkdocs_click/_docs.py
  mkdocs_click/_extension.py
  tests/app/expected-enhanced.md
  tests/test_extension.py
Labels: changelog/Added, enhancement
